server:
  port: 8000
spring:
  application:
    name: ms-order
  data:
    mongodb:
      uri: mongodb://rian:rian@localhost:27017/ms-orders?authSource=admin
      database: ms-orders
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true
  kafka:
    bootstrap-servers: localhost:9092
provider:
  address:
    url: http://viacep.com.br/ws
