server:
  port: 8000
spring:
  application:
    name: ms-order
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/ms-orders
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true
